apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  serviceAccountName: nginx-deployment-sa   # Must run as SA with access policy
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      # Mount secret to math. Filename will be objectName or objectAlias if defined.
    - name: secrets-store-inline
      mountPath: "/secrets-store"
      readOnly: true
    env:
      # Mount username as env variable
      - name: MYUSERNAME
        valueFrom:
          secretKeyRef:
            name: "myusername"
            key: username
      # Mount entire content of secret in to env variable
      - name: MY_SECRET
        valueFrom:
          secretKeyRef:
            name: "myk8ssecrets"
            key: "mysecrets"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    # Create a volume from the secret
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secret-to-k8s-secret"
status: {}