apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: username
      type: Opaque
      data: 
        - objectName: "Username"
          key: "Username"
    - secretName: mysecret
      type: Opaque
      data: 
        - objectName: "secret-token"
          key: "secretData"
  parameters:
    objects: |
        - objectName: "MySecret"  # Name of the secret in AWS secretsmanager
          objectType: "secretsmanager"
          objectAlias: secret-token      # Optional Alias name. This will be the file name on the pod
          jmesPath:                      # Use jmesPath to create file with individual secret value
            - path: "username"           # Name of the secret object in MySecret
              objectAlias: "Username"    # Name of the file that will contain the value
            - path: "password"
              objectAlias: "MyPassword"
  secretObjects:
    # Below will result in secret being created in k8s
    - secretName: username
      type: Opaque
      data: 
        - objectName: "Username"
          key: "Username"
    - secretName: mysecret
      type: Opaque
      data: 
        - objectName: "secret-token"
          key: "secretData"

      